-- movie
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (1,'0','극장판 요괴워치: 하늘을 나는 고래와 더블세계다냥!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (2,'0','교섭','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (3,'0','조제, 호랑이 그리고 물고기들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (4,'0','인터스텔라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (5,'0','해리포터와 마법사의 돌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (6,'0','레전드 오브 타잔','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (7,'0','소수의견','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (8,'0','남은 인생 10년','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (9,'0','패왕별희 디 오리지널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (10,'0','배트맨 대 슈퍼맨: 저스티스의 시작','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (11,'0','미나리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (12,'0','여름날 우리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (13,'1','악녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (14,'0','#살아있다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (15,'0','비와 당신의 이야기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (16,'0','블랙머니','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (17,'0','경관의 피','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (18,'0','체르노빌 1986','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (19,'0','지오스톰','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (20,'0','오케이 마담','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (21,'0','지랄발광 17세','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (22,'0','에베레스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (23,'0','우연과 상상','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (24,'0','인생은 아름다워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (25,'0','외계+인 1부','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (26,'0','화양연화','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (27,'1','악인전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (28,'0','노아의 방주: 남겨진 녀석들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (29,'0','말모이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (30,'0','레드슈즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (31,'0','에브리씽 에브리웨어 올 앳 원스+','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (32,'0','너의 췌장을 먹고 싶어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (33,'1','버닝','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (34,'0','베테랑','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (35,'0','노트북','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (36,'0','군함도','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (37,'0','브로커','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (38,'0','천문: 하늘에 묻는다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (39,'0','미스 페레그린과 이상한 아이들의 집','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (40,'0','피터와 드래곤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (41,'0','그린 북','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (42,'0','해치지않아','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (43,'0','극장판 귀멸의 칼날: 무한열차편','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (44,'0','서복','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (45,'0','히말라야','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (46,'0','거미줄에 걸린 소녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (47,'0','탑건: 매버릭','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (48,'0','인질','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (49,'0','갓 오브 이집트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (50,'0','터널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (51,'0','도굴','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (52,'0','웅남이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (53,'0','크롤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (54,'0','신비한 동물들과 덤블도어의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (55,'0','원더','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (56,'1','셰이프 오브 워터: 사랑의 모양','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (57,'0','매직빈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (58,'0','스파이더맨: 파 프롬 홈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (59,'0','판의 미로 - 오필리아와 세 개의 열쇠','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (60,'0','극장판 헬로카봇 : 백악기 시대','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (61,'0','발레리안: 천 개 행성의 도시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (62,'0','라스트 위치 헌터','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (63,'0','혼숨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (64,'0','가디언즈 오브 갤럭시: Volume 3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (65,'0','더 배트맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (66,'0','스포트라이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (67,'0','바이스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (68,'1','내부자들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (69,'0','스타트렉 비욘드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (70,'1','다만 악에서 구하소서 파이널컷','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (71,'0','증인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (72,'0','미녀와 야수','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (73,'0','무현, 두 도시 이야기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (74,'0','매직브러시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (75,'0','다이노소어 어드벤처 : 백악기 공룡대백과','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (76,'0','남매의 여름밤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (77,'0','안테벨룸','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (78,'0','창궐','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (79,'0','교회오빠','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (80,'1','원스 어폰 어 타임... 인 할리우드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (81,'0','명탐정 피카츄','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (82,'0','쥬라기 월드: 도미니언','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (83,'0','어린 의뢰인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (84,'0','극장판 포켓몬스터 뮤츠의 역습 EVOLUTION','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (85,'1','인민을 위해 복무하라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (86,'0','어벤져스: 에이지 오브 울트론','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (87,'0','마이펫의 이중생활','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (88,'0','패러렐 마더스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (89,'0','스머프: 비밀의 숲','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (90,'0','변신','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (91,'0','버즈 라이트이어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (92,'0','고스트버스터즈 라이즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (93,'0','이터널스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (94,'0','놉','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (95,'0','가디언즈 오브 갤럭시 VOL. 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (96,'0','터닝메카드W: 블랙미러의 부활','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (97,'0','괴물의 아이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (98,'0','라스트 크리스마스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (99,'0','극장판 안녕 자두야: 제주도의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (100,'0','수어사이드 스쿼드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (101,'0','너와 100번째 사랑','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (102,'0','인디펜던스 데이 : 리써전스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (103,'0','7년의 밤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (104,'0','슈퍼배드 3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (105,'0','가려진 시간','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (106,'0','사냥','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (107,'0','그날, 바다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (108,'0','프로페서 앤 매드맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (109,'0','메멘토','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (110,'0','아기공룡 둘리-얼음별 대모험','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (111,'0','캡틴 아메리카: 시빌 워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (112,'0','1917','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (113,'0','악의 연대기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (114,'0','파리의 인어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (115,'0','다크 나이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (116,'0','007 노 타임 투 다이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (117,'0','스펜서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (118,'0','신비아파트 극장판 하늘도깨비 대 요르문간드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (119,'0','극장판 짱구는 못말려: 신혼여행 허리케인~ 사라진 아빠!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (120,'0','레고 닌자고 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (121,'0','명탐정 코난:진홍의 연가','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (122,'0','극장판 포켓몬스터 너로 정했다!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (123,'0','블랙 팬서: 와칸다 포에버','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (124,'0','부활','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (125,'0','동주','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (126,'0','인어공주','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (127,'0','오빠생각','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (128,'0','픽셀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (129,'0','무서운 이야기 3 : 화성에서 온 소녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (130,'0','령 : 저주받은 사진','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (131,'0','옥자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (132,'0','비스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (133,'0','서치 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (134,'0','암수살인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (135,'0','장수상회','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (136,'0','공범자들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (137,'0','미스 사이공 : 25주년 특별 공연','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (138,'0','극장판 도라에몽: 진구의 신공룡','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (139,'0','이모티: 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (140,'0','콜레트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (141,'0','1987','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (142,'0','배트맨 비긴즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (143,'0','저 산 너머','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (144,'0','데자뷰','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (145,'0','엑스맨: 아포칼립스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (146,'0','온워드: 단 하루의 기적','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (147,'0','해빙','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (148,'0','굿바이 싱글','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (149,'0','덕혜옹주','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (150,'0','신과함께-죄와 벌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (151,'0','원더 우먼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (152,'0','좋아해줘','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (153,'0','짱구는 못말려 극장판 : 정면승부! 로봇아빠의 역습','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (154,'0','당갈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (155,'0','세자매','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (156,'0','대립군','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (157,'0','미드나이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (158,'0','안녕 베일리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (159,'0','반도','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (160,'0','더 박스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (161,'0','최면','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (162,'0','인시디어스 3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (163,'0','극장판 요괴워치: 탄생의 비밀이다냥!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (164,'0','그집','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (165,'1','아이 엠 어 히어로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (166,'0','리바운드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (167,'0','중경삼림','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (168,'0','대호','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (169,'0','82년생 김지영','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (170,'0','너의 이름은.','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (171,'0','13시간','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (172,'0','특송','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (173,'0','정글북','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (174,'0','보안관','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (175,'0','루카','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (176,'0','BIFAN2019 판타스틱 단편 걸작선 1','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (177,'0','콰이어트 플레이스 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (178,'0','마이 스파이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (179,'0','미니언즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (180,'0','블랙 팬서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (181,'1','범죄도시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (182,'0','n번째 이별 중','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (183,'0','쿵푸팬더3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (184,'0','빅 위시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (185,'0','인베이젼 2020','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (186,'0','시카리오: 데이 오브 솔다도','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (187,'0','히트맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (188,'0','로망','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (189,'0','뽀로로 극장판 보물섬 대모험','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (190,'0','빅 2: 황금열쇠 대소동','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (191,'0','독전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (192,'0','언더월드: 블러드 워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (193,'0','해리포터와 아즈카반의 죄수','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (194,'0','극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (195,'0','호텔 레이크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (196,'0','뮨: 달의 요정','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (197,'0','궁합','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (198,'0','압꾸정','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (199,'0','조작된 도시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (200,'0','사랑하기 때문에','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (201,'0','캔디맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (202,'0','그린랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (203,'0','컨저링 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (204,'0','극한직업','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (205,'1','드라이브','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (206,'0','47미터 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (207,'0','오! 문희','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (208,'0','장르만 로맨스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (209,'0','알라딘','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (210,'0','극비수사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (211,'0','극장판 안녕 자두야','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (212,'0','스즈메의 문단속','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (213,'0','위플래쉬','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (214,'1','레드 스패로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (215,'0','저스티스 리그','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (216,'0','투모로우랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (217,'0','원더 우먼 1984','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (218,'0','내일의 기억','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (219,'0','굿 라이어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (220,'0','드라이브 마이 카','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (221,'0','파벨만스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (222,'1','로건','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (223,'0','귀문','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (224,'0','뽀로로 극장판 드래곤캐슬 대모험','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (225,'0','미니언즈2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (226,'0','인페르노','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (227,'1','바빌론','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (228,'0','상견니','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (229,'0','안도 타다오','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (230,'0','빌리와 용감한 녀석들 3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (231,'1','캐롤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (232,'0','굴뚝마을의 푸펠','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (233,'0','귀멸의 칼날: 상현집결, 그리고 도공 마을로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (234,'0','마이펫의 이중생활 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (235,'0','몬스터 패밀리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (236,'0','인천상륙작전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (237,'0','더 보이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (238,'0','유열의 음악앨범','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (239,'0','원더스트럭','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (240,'0','코다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (241,'0','극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (242,'0','동감','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (243,'0','장화신은 고양이: 끝내주는 모험','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (244,'0','매트릭스: 리저렉션','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (245,'0','공작','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (246,'0','얼리맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (247,'0','스파이 지니어스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (248,'0','커다랗고 커다랗고 커다란 배','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (249,'0','벽 속에 숨은 마법시계','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (250,'0','육사오(6/45)','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (251,'0','히든 피겨스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (252,'0','톰과 제리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (253,'0','알리타: 배틀 엔젤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (254,'0','미스 슬로운','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (255,'0','극장판 주술회전 0','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (256,'0','스트레스 제로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (257,'1','불릿 트레인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (258,'0','이터널 선샤인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (259,'1','레지던트 이블: 파멸의 날','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (260,'0','한 솔로: 스타워즈 스토리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (261,'0','캡틴 마블','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (262,'0','더 스파이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (263,'0','캐리비안의 해적: 죽은 자는 말이 없다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (264,'1','50가지 그림자: 해방','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (265,'0','암살','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (266,'0','눈의 여왕 3: 눈과 불의 마법대결','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (267,'0','극장판 5등분의 신부','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (268,'0','소년시절의 너','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (269,'0','곰돌이 푸 다시 만나 행복해','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (270,'0','은밀한 유혹','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (271,'0','엘리멘탈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (272,'0','사라진 시간','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (273,'0','라이언','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (274,'0','스파이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (275,'0','명탐정 코난: 비색의 탄환','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (276,'0','사도','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (277,'0','결백','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (278,'0','투 프렌즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (279,'0','오션스8','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (280,'0','스탠바이, 웬디','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (281,'0','커뮤터','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (282,'0','해피 뉴 이어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (283,'0','앵그리버드 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (284,'0','더 터닝','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (285,'0','대배우','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (286,'0','조제','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (287,'0','킬링 로맨스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (288,'0','장사리 : 잊혀진 영웅들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (289,'0','미이라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (290,'0','귀멸의 칼날: 주합회의·나비저택 편','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (291,'0','트루스 오어 데어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (292,'0','다이노 타임','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (293,'0','분노의 질주: 더 세븐','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (294,'0','스타 이즈 본','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (295,'0','앤트맨과 와스프','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (296,'0','다만 악에서 구하소서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (297,'0','공각기동대 : 고스트 인 더 쉘','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (298,'1','극적인 하룻밤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (299,'0','딥','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (300,'0','넛잡 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (301,'0','스파이더맨: 홈 커밍','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (302,'0','프리 가이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (303,'0','몬스터 호텔 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (304,'0','애드 아스트라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (305,'0','레버넌트: 죽음에서 돌아온 자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (306,'0','컴백홈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (307,'0','페르디난드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (308,'0','뷰티 인사이드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (309,'0','이퀄스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (310,'0','파티마의 기적','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (311,'0','21 브릿지: 테러 셧다운','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (312,'0','설리: 허드슨강의 기적','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (313,'0','검사외전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (314,'0','극장판 헬로카봇 : 달나라를 구해줘!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (315,'0','브리짓 존스의 베이비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (316,'0','하늘을 걷는 남자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (317,'1','남과 여','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (318,'0','검은 사제들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (319,'0','해어화','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (320,'1','할로윈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (321,'0','레이디 버드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (322,'0','인랑','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (323,'0','에브리씽 에브리웨어 올 앳 원스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (324,'0','명탐정 코난: 감청의 권','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (325,'1','아가씨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (326,'1','더 수어사이드 스쿼드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (327,'0','내안의 그놈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (328,'0','다크 워터스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (329,'0','인 더 하이츠','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (330,'0','슈퍼 마리오 브라더스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (331,'0','코코','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (332,'0','샌 안드레아스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (333,'0','하트 오브 더 씨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (334,'0','조선마술사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (335,'0','트롤: 월드 투어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (336,'0','로그 원: 스타워즈 스토리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (337,'0','분노의 질주: 더 익스트림','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (338,'0','범블비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (339,'0','명탐정 코난: 할로윈의 신부','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (340,'0','극장판 엉덩이 탐정: 수플레 섬의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (341,'0','닥터 스트레인지','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (342,'0','감쪽같은 그녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (343,'0','아인보: 아마존의 전설','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (344,'0','범죄도시2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (345,'0','100% 울프: 푸들이 될 순 없어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (346,'0','어린왕자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (347,'0','보스 베이비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (348,'0','히트맨: 에이전트 47','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (349,'0','아네트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (350,'0','미스비헤이비어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (351,'0','검객','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (352,'1','지푸라기라도 잡고 싶은 짐승들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (353,'0','나미야 잡화점의 기적','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (354,'0','고스트 오브 워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (355,'0','챔피언','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (356,'0','카시오페아','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (357,'0','언차티드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (358,'0','한산: 용의 출현','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (359,'0','인턴','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (360,'0','걸캅스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (361,'0','킹메이커','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (362,'0','협상','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (363,'0','드래곤 길들이기 3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (364,'0','뱅가드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (365,'0','재심','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (366,'0','국가부도의 날','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (367,'1','여교사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (368,'0','탄생','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (369,'1','상류사회','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (370,'0','더 서클','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (371,'0','자전차왕 엄복동','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (372,'0','완벽한 타인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (373,'0','주토피아','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (374,'0','터미네이터 제니시스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (375,'0','사바하','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (376,'0','나를 찾아줘','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (377,'0','미스터 주: 사라진 VIP','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (378,'0','더 프롬','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (379,'0','퍼피 구조대 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (380,'0','명탐정 코난: 진홍의 수학여행','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (381,'0','베놈 2: 렛 데어 비 카니지','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (382,'0','판도라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (383,'0','형','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (384,'0','토르: 라그나로크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (385,'0','러빙 빈센트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (386,'0','나의 소녀시대','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (387,'0','극장판 시그널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (388,'0','남산의 부장들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (389,'0','더 페이버릿: 여왕의 여자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (390,'1','존 윅 4','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (391,'0','미드웨이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (392,'0','강철비2: 정상회담','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (393,'0','싱크홀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (394,'0','피는 물보다 진하다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (395,'0','무한대를 본 남자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (396,'0','카일라스 가는 길','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (397,'1','간신','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (398,'0','토이 스토리 4','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (399,'0','공조2: 인터내셔날','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (400,'0','카오스 워킹','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (401,'0','덤보','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (402,'0','고속도로 가족','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (403,'0','탐정 홍길동: 사라진 마을','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (404,'0','유체이탈자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (405,'0','조커','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (406,'0','애나벨 집으로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (407,'0','플립','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (408,'0','스파이더맨: 어크로스 더 유니버스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (409,'0','시맨틱 에러: 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (410,'0','페이트 스테이 나이트 헤븐즈필 제3장 스프링 송','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (411,'0','레오나르도 다 빈치','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (412,'0','러브 유어셀프 인 서울','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (413,'0','씽','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (414,'0','고질라 VS. 콩','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (415,'0','마션','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (416,'0','리틀드래곤 코코넛','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (417,'0','앤트맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (418,'0','아무튼, 아담','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (419,'0','극장판 바다 탐험대 옥토넛 : 불의 고리 대폭발','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (420,'0','문폴','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (421,'0','어스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (422,'0','신과함께-인과 연','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (423,'0','고녀석 맛나겠다2 : 함께라서 행복해','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (424,'0','오피스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (425,'0','꾼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (426,'0','위험한 상견례 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (427,'0','샤잠!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (428,'0','미쓰 와이프','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (429,'0','혹성탈출: 종의 전쟁','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (430,'1','내부자들: 디 오리지널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (431,'0','스윙키즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (432,'0','컴온 컴온','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (433,'0','프렌즈: 둥지탈출','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (434,'0','명탐정 코난: 순흑의 악몽','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (435,'0','옥수역귀신','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (436,'0','아바타 리마스터링','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (437,'0','마녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (438,'0','대장 김창수','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (439,'0','포레스트: 죽음의 숲','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (440,'0','언더워터','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (441,'1','데드풀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (442,'0','영웅','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (443,'1','늑대사냥','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (444,'0','젠틀맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (445,'0','눈의 여왕4','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (446,'0','엔칸토: 마법의 세계','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (447,'0','뜨거운 피','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (448,'0','라이온 킹','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (449,'0','고장난 론','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (450,'0','시동','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (451,'0','미씽: 사라진 여자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (452,'0','퍼펙트맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (453,'0','귀향','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (454,'0','보통사람','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (455,'0','도리를 찾아서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (456,'0','앨빈과 슈퍼밴드: 악동 어드벤처','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (457,'0','원더풀 고스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (458,'0','라라랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (459,'0','엽문4: 더 파이널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (460,'0','고백','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (461,'0','치킨래빗: 잃어버린 보물을 찾아서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (462,'0','자백','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (463,'0','월요일이 사라졌다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (464,'0','소울','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (465,'0','성난황소','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (466,'0','국제수사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (467,'1','해피 투게더','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (468,'1','랑종','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (469,'0','다이노X 탐험대','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (470,'0','마크맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (471,'0','나이브스 아웃','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (472,'1','차이나타운','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (473,'0','애스터로이드 시티','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (474,'0','타오르는 여인의 초상','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (475,'0','스파이 브릿지','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (476,'1','귀공자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (477,'1','데드풀 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (478,'0','안녕, 나의 소녀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (479,'0','헤어질 결심','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (480,'0','봉오동 전투','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (481,'0','시간이탈자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (482,'0','그래비티','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (483,'0','앤트맨과 와스프: 퀀텀매니아','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (484,'0','소리꾼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (485,'0','기억의 밤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (486,'0','분노의 질주: 더 얼티메이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (487,'0','터미네이터: 다크 페이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (488,'0','인크레더블 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (489,'0','청년경찰','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (490,'0','덩케르크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (491,'0','마음이 외치고 싶어해','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (492,'0','나의 특별한 형제','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (493,'0','정글 크루즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (494,'0','괴기맨숀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (495,'0','미션 파서블','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (496,'0','삼진그룹 영어토익반','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (497,'1','나의 절친 악당들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (498,'1','나쁜 녀석들: 포에버','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (499,'0','롱 리브 더 킹: 목포 영웅','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (500,'1','라스트 나잇 인 소호','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (501,'0','허스토리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (502,'0','램','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (503,'0','번개맨과 신비의 섬','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (504,'1','두 남자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (505,'0','미션 임파서블: 폴아웃','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (506,'0','보스 베이비 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (507,'0','문라이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (508,'0','리멤버','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (509,'0','닥터 스트레인지: 대혼돈의 멀티버스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (510,'0','2022 영탁 단독 콘서트 \"탁쇼\"','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (511,'0','나우 유 씨 미 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (512,'0','신데렐라 2: 마법에 걸린 왕자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (513,'0','레디 플레이어 원','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (514,'0','수퍼 소닉2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (515,'0','신비한 동물들과 그린델왈드의 범죄','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (516,'0','갤로우즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (517,'0','바울','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (518,'0','나이트메어 앨리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (519,'1','불한당: 나쁜 놈들의 세상','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (520,'1','존 윅 3: 파라벨룸','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (521,'0','비상선언','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (522,'0','바다 탐험대 옥토넛 : 육지수호 대작전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (523,'0','콩: 스컬 아일랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (524,'0','아임 히어로 더 파이널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (525,'0','카페 벨에포크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (526,'0','어글리 돌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (527,'0','원샷','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (528,'0','해피 데스데이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (529,'0','명당','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (530,'0','해적: 도깨비 깃발','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (531,'0','특별시민','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (532,'0','나랏말싸미','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (533,'0','드림','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (534,'0','쥬라기 월드: 폴른 킹덤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (535,'0','파이프라인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (536,'0','어쩌다, 결혼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (537,'0','나의 청춘은 너의 것','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (538,'0','러브 앳','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (539,'0','분노의 질주: 라이드 오어 다이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (540,'0','라자루스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (541,'0','극장판 파워레인저: 닌자포스 VS 트레인포스 닌자 인 원더랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (542,'0','가버나움','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (543,'0','광대들: 풍문조작단','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (544,'0','극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (545,'0','양자물리학','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (546,'0','닥터 두리틀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (547,'0','고스트버스터즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (548,'0','스틸 앨리스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (549,'0','23 아이덴티티','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (550,'0','더 퍼스트 슬램덩크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (551,'0','오늘 밤, 세계에서 이 사랑이 사라진다 해도','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (552,'0','뽀로로 극장판 공룡섬 대모험','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (553,'0','노무현입니다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (554,'0','아쿠아맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (555,'0','극장판 뽀로로와 친구들: 바이러스를 없애줘!','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (556,'0','방탄소년단: 옛 투 컴 인 시네마','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (557,'0','반드시 잡는다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (558,'0','어벤져스: 엔드게임','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (559,'0','수색자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (560,'0','로스트 인 더스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (561,'0','페어웰','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (562,'0','기생충','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (563,'0','점박이 한반도의 공룡2 : 새로운 낙원','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (564,'0','분노의 질주: 홉스&쇼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (565,'0','씽2게더','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (566,'0','셜록: 유령신부','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (567,'0','택시운전사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (568,'0','멍뭉이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (569,'0','극장판 바이올렛 에버가든','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (570,'0','리미트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (571,'0','방법: 재차의','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (572,'0','원피스 필름 레드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (573,'0','대외비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (574,'0','극장판 도라에몽: 진구의 우주소전쟁 리틀스타워즈 2021','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (575,'0','컨택트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (576,'0','태일이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (577,'0','장난스런 키스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (578,'0','소리도 없이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (579,'0','엑시트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (580,'0','고질라: 킹 오브 몬스터','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (581,'0','항거:유관순 이야기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (582,'1','맨 인 더 다크 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (583,'0','더 레이서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (584,'0','트롤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (585,'0','작은 아씨들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (586,'0','용과 주근깨 공주','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (587,'0','이프 온리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (588,'1','직쏘','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (589,'0','모가디슈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (590,'0','메이즈 러너: 스코치 트라이얼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (591,'0','주디','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (592,'0','이상한 나라의 수학자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (593,'0','신데렐라:마법 반지의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (594,'0','정직한 후보','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (595,'0','나는 나를 해고하지 않는다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (596,'0','프리즌 이스케이프','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (597,'0','특별수사: 사형수의 편지','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (598,'0','그린치','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (599,'0','7번째 내가 죽던 날','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (600,'0','눈길','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (601,'0','밀정','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (602,'1','리얼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (603,'0','내 사랑','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (604,'0','리틀 프린세스 소피아 : 신비한 섬','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (605,'0','미쓰백','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (606,'0','메간','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (607,'1','킹스맨: 퍼스트 에이전트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (608,'0','리틀메딕: 몸속탐험대','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (609,'0','노매드랜드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (610,'0','싱글라이더','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (611,'0','미드나잇 선','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (612,'0','날씨의 아이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (613,'0','아더와 미니모이 3: 두 세계의 전쟁','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (614,'0','임금님의 사건수첩','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (615,'0','마스터','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (616,'0','목격자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (617,'0','최강전사 미니특공대: 영웅의 탄생','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (618,'0','덕구','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (619,'0','짱구는 못말려 극장판: 폭풍수면! 꿈꾸는 세계 대돌격','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (620,'0','어바웃 타임','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (621,'1','아토믹 블론드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (622,'0','발신제한','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (623,'0','천로역정: 천국을 찾아서','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (624,'0','탐정: 리턴즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (625,'0','아바타: 물의 길','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (626,'0','크레이지 리치 아시안','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (627,'0','부라더','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (628,'0','지금 만나러 갑니다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (629,'0','극장판 미니특공대: 햄버거괴물의 습격','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (630,'0','백두산','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (631,'0','데스노트: 더 뉴 월드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (632,'0','더 셰프','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (633,'0','어나더 라운드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (634,'0','플래시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (635,'0','오토라는 남자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (636,'0','12 솔져스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (637,'0','콰이어트 플레이스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (638,'0','정직한 후보2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (639,'0','마야2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (640,'0','PMC: 더 벙커','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (641,'0','메카닉: 리크루트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (642,'0','크루엘라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (643,'1','젠틀맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (644,'0','위대한 소원','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (645,'0','선생님의 일기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (646,'0','말레피센트 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (647,'0','글로리데이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (648,'0','미스터트롯: 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (649,'0','소피와 드래곤: 마법책의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (650,'0','로봇, 소리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (651,'0','그놈이다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (652,'0','더 폰','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (653,'0','인시디어스4: 라스트 키','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (654,'0','라야와 마지막 드래곤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (655,'0','사자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (656,'0','던전 앤 드래곤: 도적들의 명예','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (657,'0','더 넌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (658,'0','염력','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (659,'0','하루','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (660,'0','강철비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (661,'0','범죄도시3','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (662,'0','토르: 마법 검의 전설','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (663,'0','애프터 양','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (664,'0','스케어리 스토리:어둠의 속삭임','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (665,'0','롱 샷','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (666,'0','눈의 여왕5: 스노우 프린세스와 미러랜드의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (667,'0','위대한 쇼맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (668,'0','뱅드림! 로젤리아 에피소드Ⅰ: 약속','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (669,'0','가재가 노래하는 곳','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (670,'1','존 윅: 특별판','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (671,'0','킬러의 보디가드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (672,'0','빅샤크3: 젤리몬스터 대소동','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (673,'0','엔시티 드림 더 무비 : 인 어 드림','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (674,'1','맨 인 더 다크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (675,'0','공기살인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (676,'0','가장 보통의 연애','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (677,'0','하우스 오브 구찌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (678,'0','사우스포','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (679,'0','듄','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (680,'1','킬러의 보디가드 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (681,'0','포켓 몬스터 DP: 아르세우스 초극의 시공으로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (682,'0','제이슨 본','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (683,'0','계춘할망','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (684,'0','나의 그리스식 웨딩 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (685,'0','탐정 : 더 비기닝','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (686,'0','명탐정코난: 하이바라 아이 이야기 ~흑철의 미스터리 트레인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (687,'0','잭 리처: 네버 고 백','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (688,'0','밤쉘: 세상을 바꾼 폭탄선언','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (689,'0','포드 V 페라리','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (690,'0','프랑스여자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (691,'1','밤의 해변에서 혼자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (692,'0','부산행','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (693,'0','스타워즈: 깨어난 포스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (694,'0','레슬러','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (695,'0','이웃사촌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (696,'0','침묵','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (697,'0','연평해전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (698,'0','블랙 아담','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (699,'0','0.0MHz','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (700,'1','프리키 데스데이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (701,'0','테넷','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (702,'0','오리엔트 특급 살인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (703,'0','500일의 썸머','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (704,'0','배드 가이즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (705,'0','컨저링3: 악마가 시켰다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (706,'0','어벤져스: 인피니티 워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (707,'0','리틀 포레스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (708,'0','쥬라기 월드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (709,'0','겨울왕국 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (710,'1','존 윅 - 리로드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (711,'0','서부전선','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (712,'0','곡성','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (713,'0','주먹왕 랄프 2: 인터넷 속으로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (714,'0','셜록 놈즈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (715,'0','그린 나이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (716,'0','아무도 없는 곳','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (717,'0','서울괴담','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (718,'0','샹치와 텐 링즈의 전설','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (719,'0','보이저스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (720,'0','로마의 휴일','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (721,'1','브이아이피','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (722,'0','런','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (723,'0','신비아파트 극장판 차원도깨비와 7개의 세계','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (724,'0','연애 빠진 로맨스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (725,'0','카운트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (726,'0','미션 임파서블: 로그네이션','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (727,'0','그대, 고맙소 : 김호중 생애 첫 팬미팅 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (728,'0','극장판 짱구는 못말려 : 습격!! 외계인 덩덩이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (729,'0','극장판 짱구는 못말려: 격돌! 낙서왕국과 얼추 네 명의 용사들','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (730,'0','메이즈 러너: 데스 큐어','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (731,'0','인셉션','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (732,'0','베이블레이드 버스트 갓 : 갓 발키리의 탄생','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (733,'0','뺑반','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (734,'0','더 보이 2: 돌아온 브람스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (735,'0','극장판 헬로카봇: 수상한 마술단의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (736,'1','시카리오: 암살자의 도시','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (737,'0','올빼미','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (738,'0','매그니피센트 7','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (739,'0','마루이 비디오','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (740,'0','브레이크 더 사일런스: 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (741,'0','베놈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (742,'0','어니스트 씨프','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (743,'0','맘마미아!2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (744,'0','블랙핑크 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (745,'0','극장판 윌벤져스 : 수상한 캠핑 대소동','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (746,'0','모비우스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (747,'0','쥬만지: 새로운 세계','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (748,'0','더 매직: 리틀톰과 도둑공주','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (749,'0','스위치','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (750,'0','안시성','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (751,'0','그것만이 내 세상','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (752,'0','유령','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (753,'0','돈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (754,'0','극장판 또봇: 로봇군단의 습격','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (755,'1','콜 미 바이 유어 네임','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (756,'0','남한산성','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (757,'1','프리즌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (758,'0','게이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (759,'0','배니싱: 미제사건','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (760,'0','모아나','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (761,'0','도리화가','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (762,'0','홈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (763,'0','매드 맥스: 분노의 도로','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (764,'0','겟 아웃','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (765,'0','열정같은소리하고있네','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (766,'0','잔칫날','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (767,'0','마녀(魔女) Part2. The Other One','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (768,'1','19곰 테드 2','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (769,'0','그대가 조국','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (770,'0','서치','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (771,'0','극장판 바다 탐험대 옥토넛 : 해저동굴 대탈출','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (772,'1','바람 바람 바람','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (773,'0','너의 결혼식','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (774,'0','침입자','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (775,'1','아수라','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (776,'0','럭키','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (777,'0','니 부모 얼굴이 보고 싶다','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (778,'0','그것: 두 번째 이야기','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (779,'0','미스컨덕트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (780,'0','울프 콜','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (781,'1','언니','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (782,'0','죽지않는 인간들의 밤','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (783,'0','블랙 위도우','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (784,'0','슈퍼 빼꼼: 스파이 대작전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (785,'0','래빗 스쿨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (786,'1','킹스맨: 골든 서클','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (787,'0','담보','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (788,'0','패신저스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (789,'0','어느 가족','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (790,'0','생일','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (791,'0','싱 스트리트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (792,'0','심야식당','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (793,'0','박열','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (794,'0','헌트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (795,'0','후드','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (796,'0','아이 캔 스피크','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (797,'0','장산범','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (798,'0','스파이더맨: 노 웨이 홈','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (799,'0','극장판 포켓몬스터: 정글의 아이, 코코','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (800,'0','더 보이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (801,'0','변산','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (802,'0','더 포스트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (803,'0','피터 래빗','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (804,'0','아이스 에이지: 지구 대충돌','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (805,'0','곤지암','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (806,'0','데시벨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (807,'0','소울메이트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (808,'0','몬스터 하우스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (809,'0','뷰티풀 투모로우','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (810,'0','아홉 스님','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (811,'0','베일리 어게인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (812,'0','보헤미안 랩소디','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (813,'0','빅샤크: 매직체인지','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (814,'0','신비아파트: 금빛 도깨비와 비밀의 동굴','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (815,'1','람보 : 라스트 워','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (816,'0','벤허','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (817,'0','인비저블맨','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (818,'0','인사이드 아웃','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (819,'0','원스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (820,'0','인디아나 존스: 운명의 다이얼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (821,'0','해길랍','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (822,'0','특수요원 빼꼼','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (823,'0','공조','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (824,'0','나쁜 녀석들: 더 무비','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (825,'1','무뢰한','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (826,'0','치외법권','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (827,'0','더 킹','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (828,'1','빅쇼트','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (829,'0','극장판 헬로카봇: 옴파로스 섬의 비밀','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (830,'0','자산어보','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (831,'0','원라인','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (832,'0','기적','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (833,'0','보이스','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (834,'0','신비한 동물사전','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (835,'0','트랜스포머: 최후의 기사','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (836,'0','미 비포 유','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (837,'0','나를 차버린 스파이','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (838,'1','나이팅게일','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (839,'0','세버그','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (840,'0','헝거게임: 더 파이널','0');
INSERT INTO `movie` (`movie_id`,`is_adulted`,`title`,`adulted`) VALUES (841,'0','라이트 아웃','0');

-- tag
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (1,'미스터리');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (2,'공포(호러)');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (3,'가족');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (4,'전쟁');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (5,'어드벤처');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (6,'스릴러');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (7,'다큐멘터리');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (8,'액션');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (9,'코미디');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (10,'공연');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (11,'SF');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (12,'사극');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (13,'뮤지컬');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (14,'애니메이션');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (15,'범죄');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (16,'드라마');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (17,'판타지');
INSERT INTO `tag` (`tag_id`,`tag_name`) VALUES (18,'멜로/로맨스');