version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd server/moviepop
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./server/moviepop/build/libs/*.jar)
artifacts:
  files:
    - server/moviepop/build/libs/*.jar
    - server/moviepop/scripts/**
    - server/moviepop/appspec.yml
  discard-paths: yes