export const data2 = [
  {
    groupId: 1,
    title: '맥주 한 캔 들고 같이 봐요 ⭐️',
    location: 'http://watcha...',
    max: 5,
    current: 2,
    date: '2023-06-30 T20:00',
    movieTitle: '고양이의 보은',
  },
  {
    groupId: 2,
    title: '동석이형 보러 진실의방으로 ⭐️',
    location: 'http://NetFlix...',
    max: 4,
    current: 2,
    date: '2023-07-14 T21:00',
    movieTitle: '범죄 도시1',
  },
  {
    groupId: 3,
    title: '뽀롱 뽀롱 뽀로로(?) ⭐️',
    location: 'http://watcha...',
    max: 4,
    current: 3,
    date: '2023-07-20 T14:00',
    movieTitle: '뽀로로 극장판 2기',
  },
  {
    groupId: 4,
    title: '코난 극장판 같이 정주행 하실분~ ⭐️',
    location: 'http://watcha...',
    max: 3,
    current: 2,
    date: '2023-07-26 T20:00',
    movieTitle: '명탐정 코난 극장판',
  },
  {
    groupId: 5,
    title: '코난 극장판 같이 정주행 하실분~ ⭐️',
    location: 'http://watcha...',
    max: 3,
    current: 2,
    date: '2023-07-26 T20:00',
    movieTitle: '명탐정 코난 극장판',
  },
  {
    groupId: 6,
    title: '코난 극장판 같이 정주행 하실분~ ⭐️',
    location: 'http://watcha...',
    max: 3,
    current: 2,
    date: '2023-07-26 T20:00',
    movieTitle: '명탐정 코난 극장판',
  },
];
